# Generated by Django 2.2.4 on 2019-11-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191103_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='img', upload_to=''),
            preserve_default=False,
        ),
    ]
